### PR TITLE
Added humidity class and HTS221 driver

### PR DESCRIPTION
**Pull request by XECDesign**
Hello,
We're using RTIMULib for the astro-pi competition (http://astro-pi.org/) and Sense HAT.
https://www.raspberrypi.org/astro-pi-flight-case/

This is one of the sensors on the board and it would be nice to get support for it upstream.

There's also a PR for the IMU coming, but that sits on top of this commit. If this one is accepted, I'll send the other so that it's easier to merge.

### CODE REVIEW

**Comment by richardbarnett** [comment]
Nice work! I didn't know if there was a reason to add the humidity support but it looks like the astro-pi hat is the reason :-). The problem I have is that I can't test this as I don't have an HTS221 and it seems that the astro-pi hat isn't available. However, given that you have put together the infrastructure to support humidity sensors in RTIMULib, I guess I need to get one. I have code for other humidity sensors that could go in also. I also need to get an LSM9DS1 it looks like.

Do you happen to know when the astro-pi hat will be generally available?

**Comment by richardbarnett** [comment]
I guess one approach in the short term is for me to merge and test that it doesn't break anything else and then maybe you can validate the merged code since you presumably have the hardware?

Incidentally, do you want a credit in the source code for this? If so let me know what you would like.

**Comment by XECDesign** [comment]
I've sent you an email on the info@ email address on your site. Regarding general availability, we hope to get them out soon-ish, maybe within the next few months. However, there are no solid dates yet.

We've been running with these changes for quite a while and the units sent to schools came with cards preloaded with the modified version of RTIMULib. Although the sample size isn't that great, there haven't been any reports of things not working as expected yet.

As far as credit goes, I'm not too fussed.

**Comment by richardbarnett** [comment]
Great. Ok, I'll get that merge sorted out.

**Comment by richardbarnett** [comment]
Regarding credit, how about if I say something like "thanks to XECDesign for the HST221 support" in the code and/or readme?

**Comment by XECDesign** [comment]
Sure, I'm happy with that. Could leave it out entirely. Whatever works for you.

**Comment by richardbarnett** [comment]
Included in V7.0.0. I noticed a missing "," in the python setup.py that preventing the library from building but that was the only change.

**Pull request closed without merging**
